### ISSUE TITLE
뉴스에서 속담 데이터 수집 &  인덱스 

### ISSUE THREAD

**Issue by eubinean** [wisdomify/storyteller#19]
## What?
빅카인즈 api를 사용해서,  wisdoms에 포함된 모든 속담의 용례를 가능한 다 찾아낸다.

## Why?
보통 뉴스에 속담의 용례가 많이 포함되어 있어서.

## To-do's
- [x] api 요청이 잘되는지 확인하기
- [x] 뉴스 데이터 수집하기 (구문 검색이 정확하지 않다면,  그냥 토큰으로 쪼개서, 불리언 검색 활용) 
- [x] 그리고 News(Story) 구현
- [x] `python3 -m storyteller.main.index --index=news_story`  인덱싱까지 마무리하기!

**Comment by teang1995** [comment]
News(Story) 구현 후 index 실행해보았는데 

```
Traceback (most recent call last):
  File "/Users/teang1995/miniforge3/envs/storyteller/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/teang1995/miniforge3/envs/storyteller/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/teang1995/codes/storyteller/storyteller/main/index.py", line 6, in <module>
    from storyteller.elastic.docs import GK, SC, MR, News, Story
  File "/Users/teang1995/codes/storyteller/storyteller/elastic/docs.py", line 11, in <module>
    class Story(Document):
  File "/Users/teang1995/codes/storyteller/storyteller/elastic/docs.py", line 16, in Story
    def stream_from_corpus() -> Generator['Story', None, None]:
TypeError: 'ABCMeta' object is not subscriptable
```
위와 같은 에러가 발생했습니다. 우선 코드 다시 보도록 하겠습니다.

**Comment by eubinean** [comment]
> News(Story) 구현 후 index 실행해보았는데 
> 
> 
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "/Users/teang1995/miniforge3/envs/storyteller/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> 
>     return _run_code(code, main_globals, None,
> 
>   File "/Users/teang1995/miniforge3/envs/storyteller/lib/python3.8/runpy.py", line 87, in _run_code
> 
>     exec(code, run_globals)
> 
>   File "/Users/teang1995/codes/storyteller/storyteller/main/index.py", line 6, in <module>
> 
>     from storyteller.elastic.docs import GK, SC, MR, News, Story
> 
>   File "/Users/teang1995/codes/storyteller/storyteller/elastic/docs.py", line 11, in <module>
> 
>     class Story(Document):
> 
>   File "/Users/teang1995/codes/storyteller/storyteller/elastic/docs.py", line 16, in Story
> 
>     def stream_from_corpus() -> Generator['Story', None, None]:
> 
> TypeError: 'ABCMeta' object is not subscriptable
> 
> ```
> 
> 위와 같은 에러가 발생했습니다. 우선 코드 다시 보도록 하겠습니다.

반환하는 값의  타입을 `Generator['News', None,None]` 로 수정해보세요.   그럼 해결될겁니다.

**Comment by teang1995** [comment]
> > News(Story) 구현 후 index 실행해보았는데
> > ```
> > 
> > Traceback (most recent call last):
> > 
> >   File "/Users/teang1995/miniforge3/envs/storyteller/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> > 
> >     return _run_code(code, main_globals, None,
> > 
> >   File "/Users/teang1995/miniforge3/envs/storyteller/lib/python3.8/runpy.py", line 87, in _run_code
> > 
> >     exec(code, run_globals)
> > 
> >   File "/Users/teang1995/codes/storyteller/storyteller/main/index.py", line 6, in <module>
> > 
> >     from storyteller.elastic.docs import GK, SC, MR, News, Story
> > 
> >   File "/Users/teang1995/codes/storyteller/storyteller/elastic/docs.py", line 11, in <module>
> > 
> >     class Story(Document):
> > 
> >   File "/Users/teang1995/codes/storyteller/storyteller/elastic/docs.py", line 16, in Story
> > 
> >     def stream_from_corpus() -> Generator['Story', None, None]:
> > 
> > TypeError: 'ABCMeta' object is not subscriptable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 위와 같은 에러가 발생했습니다. 우선 코드 다시 보도록 하겠습니다.
> 
> Generator['News', None,None]
> 
> 으로 수정해보세요!

앗, Story class의 return type도 저렇게 수정해야 하나요? 저게 지금 Story 클래스에서 난 에러거든요.

**Comment by ArtemisDicoTiar** [comment]
@teang1995 용택님 해당 코드에서 클래스메소드로 사용되었는데 "@staticmethod"로 데코레이트되어 있는 부분이 있네요. 해당 부분 수정하면 문제 해결될 듯합니다! :)

**Comment by teang1995** [comment]
> @teang1995 용택님 해당 코드에서 클래스메소드로 사용되었는데 "@staticmethod"로 데코레이트되어 있는 부분이 있네요. 해당 부분 수정하면 문제 해결될 듯합니다! :)

감사합니다! 수정해서 푸쉬했습니다!
