### ISSUE TITLE
고려대 코퍼스로 수집한 데이터도 ES에 업로드하기

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [wisdomify/storyteller#20]
## TL;DR
기존에 수집한 데이터도 활용해보자.

## WHY?
기존에 수집한 자료도 유의미하다. 

## WHAT?
고로 막 버리지 말고 ES에 또다른 인덱스로 올리자

## TODOs
- [x] 기존에 수집했던 데이터 다시 로컬에 모으기
- [x] tsv로드해서 json으로 변환하는 로직 넣기
- [x] tsv to json 스크립트로 기존 tsv를 elastic에 저장할 수 있는 form으로 변환하기
- [x] 변환된 json ES에 indexing하기

**Comment by ArtemisDicoTiar** [comment]
요번껀 지난번에 작성한 csv support를 사용하지 않고 바로 pandas load 하게 해보자
