### ISSUE TITLE
wandb Tables 적용하기

### ISSUE THREAD

**Issue by eubinean** [wisdomify/storyteller#23]
## What?

wandb Tables를 활용하여 builders.py 완성하기.

## Why? 

wandb에서 제공하는 [Tables 객체](https://docs.wandb.ai/guides/data-vis/log-tables#create-tables)를 활용하면, 굳이 로컬에다가 tsv파일을 저장하지 않아도, 바로 데이터를 wandb에 푸시할 수 있다. 접근을 하는 방법도 마찬가지. 굳이 path를 지정할 필요가 없어, 훨씬 더 간결해진다는 점이 장점.

## To-do's
- [x]  Tables 문서 리뷰하기
- [x] augment , parse  함수를 추가하기 - `Wisdom2EgUploader`의 경우에 한함!, normalise 함수 구현하기
- [x] elastic/utils.py -> elastic/crud.py
- [x] builders.py 추가
