### ISSUE TITLE
wisdomify_test의 일부분을 validation으로 사용하는 것으로 변경하기

### ISSUE THREAD

**Issue by eubinean** [wisdomify/storyteller#35]
## What?
- wisdom2def, wisdom2eg -> raw, all로만 분할.
- wisdomify_test -> raw, all, test, val로 분할.
- 이렇게 하면, early stopping으로 에폭을 최적화하는 것이 가능하다. 
- validation set의 비율은 20%로 하자. 100개 중 20개를 validation에 사용한다.

## Why? 

최종적으로 풀고자하는 문제는 `wisdom2test`인데, validation셋을  `wisdom2def`의 일부분으로 사용해버리면, 최종문제에 대하여 
언제 오버피팅이 되는지 확인할 수 있는 길이 없다.

## To-do's - the tasks
- [x] wisdom2test -> wisdomify_test 이름 재변경
- [x] 이게 더 적절할듯 -> wisdomify_test - >wisdom2query
- [x] stratified_split 구현하기
- [x] wisdom2def, wisdom2eg -> raw, all로만 분할하기
- [x] wisdomify_test -> raw, all, val, test로만 분할하기

## To -do's - some simple refactoring
- [x] 각 artifact별로, 중요한 메타데이터 추가하기 (e.g.  wisdomify_test의 경우 -> val_ratio, seed)
- ~[ ] flatten out the data directory (data/corpora, data/wandb  -> copora,  wandb) - flat is better than nested~ 폴더가 알파벳 순서로 정렬... 오히려 더 지저분해짐. 그냥 냅두자.
