### ISSUE TITLE
ai-hub 짝수번째 데이터 전처리 및 업로드

### ISSUE THREAD

**Issue by teang1995** [wisdomify/storyteller#9]
### 왜 업로드 하는지?
- ES에 올릴 데이터를 많이 긁어모아야 한다! ai-hub에는 "속담이 있을 법한" 데이터들이 여럿 보이는데, 이를 일단 모조리 올린 후 속담이 있는 데이터만 사용하려 함.

### 왜 전처리 해야하는지?
- 우리가 사용하는 폼대로 모두 `sentence`에 한 문장만 있으면 좋지만.. 현실은 그리 녹록치 않더라. 각 데이터에 맞게 업로드 하는 방법을 명시해두어야 나중에 가져올 일이 있다면 편리하게 가져올 수 있을 듯 하다.

## WHAT?
- ai-hub의 자연어/음성 데이터에 짝수 번째 데이터 중, 속담이 있을 법한 데이터를 긁어 각 데이터에서 문장만 가져올 수 있는 방법을 정리한다.
- 또한, 전처리한 데이터를 ES cloud에 bulk api를 이용하여 업로드한다.

## TODOs
- [x]  ~~고객 응대 음성~~
- [x]  ~~공공행정문서 OCR~~
- [x]  도서자료 기계독해 - 8
- [x]  ~~논문 자료 요약~~
- [x]  ~~명령어 음성 - 노인 남녀~~
- [x]  ~~명령어 음성 - 일반 남녀~~
- [x]  ~~민원(콜센터) 질의 - 응답~~
- [x]  ~~상담 음성~~
- [x]  ~~소상공인 고객 주문 질의-응답 텍스트~~
- [x]  ~~시각 정보 기반 질의응답~~
- [x]  일반 상식
- [x]  ~~자유대화 음성(소아, 유아)~~
- [x]  전문 분야 한영 말뭉치
- [x]  ~~차량 내 대화 및 명령어 음성~~
- [x]  한국어 SNS
- [x]  한국어 대화
- [x]  ~~한국어 방언 발화(강원도)~~
- [x]  ~~한국어 방언 발화(전라도)~~
- [x]  ~~한국어 방언 발화(충청도)~~
- [x]  한국어-영어 번역 말뭉치 (기술과학)
- [x]  한국어-영어 번역(병렬) 말뭉치
- [x]  ~~한국어-중국어 번역 말뭉치(기술 과학)~~
- [x]  ~~한국인 대화 음성~~
- [x]  ~~회의 음성~~

**Comment by teang1995** [comment]
### 도서 자료 기계 독해 - 문장만 빼오기

```
for json_file_name in os.listdir(data_dir):
    json_path = path.join(data_dir, json_file_name)
    with open(json_path, 'r', encoding='utf-8') as json_file:
        json_data = json.load(json_file)
        sentences_info = json_data['sentence']
        for sentence_info in sentences_info:
            sentence = sentence_info['text']
            if sentence.endswith('.'):
                print(sentence)
'''
result

케냐 공화국 또는 케냐(Kenya)는 동아프리카의 공화국이다.
인도양에 면해 있으며 북동쪽으로 소말리아, 북쪽으로 에티오피아와 남수단, 서쪽으로 우간다, 남쪽으로 탄자니아와 국경을 맞닿고 있다.
수도는 나이로비이며 공용어는 영어와 스와힐리어이다.
케냐의 주요 종족은 키쿠유족, 루히아족, 루오족, 칼렌진족, 캄바족, 키시족,메루족 등 여러 민족으로 구성되어 있어 각각 다른 언어를 사용한다.
백인, 인도인, 아랍인 등 비아프리카계 민족은 전체 인구의 1% 정도를 차지한다.
인구는 4,403만 명(2013년 7월,CIA 추정자료)이다.
동아프리카에서 발견된 화석에 따르면 조상이 2백만 년 전 이 지역에서 살았다고 한다.
투르카나 호 근처에서의 최근 발굴에 따르면 호모 하빌리스(Homo habilis), 호모 에렉투스(Homo erectus)와 같은 호미니드인(hominid)이 260만 년 전 이 나라 땅에 있었다.
케냐의 식민 시대 역사는 1885년 독일이 잔지바르(현 탄자니아의 잔지바르 섬) 술탄의 케냐 해안 영토에 보호령을 설치한 것으로 시작되었다.
...
'''
```

**Comment by teang1995** [comment]
### 자유대화 음성(소아, 유아)
![image](https://user-images.githubusercontent.com/23451721/137599986-61083a8c-40ce-4b14-8ae9-07ff7227ce75.png)
앗.. 용량 멈춰!
일단 보류

**Comment by ArtemisDicoTiar** [comment]
@teang1995 용택님! gcp에 다운로드 다해놔서 제가 작성한 클래스로 다운받으면 될거같아요!

https://github.com/wisdomify/storyteller/blob/de6f3d48178c5812f22f643f417fdc129c20988a/storyteller/utils/gcp_dataloader.py#L129-L130

**Comment by ArtemisDicoTiar** [comment]
끝
